name: Get Citation Data

on: 
  page_build: 
  schedule:
    - cron: '0 8 * * 1'  # 每周一08:00 UTC运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Reqs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools python3-pip git
    - name: Install Python Packages
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
    - name: Run
      run: |
        cd ./google_scholar_crawler
        python3 main.py
        cd ./results
        
        # Initialize Git repository if not already initialized
        if [ ! -d .git ]; then
          git init
        fi
        
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        
        git add *.json
        git commit -m "Updated Citation Data"
        
        # Enable verbose output for debugging
        git push "${remote_repo}" HEAD:google-scholar-stats --force --verbose
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GO​⬤
